server {
  set $forward_scheme http;
  set $server         "10.128.0.4";
  set $port           8090;

  listen 80;
  listen [::]:80;

  server_name programmingintelligence.org;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_pass       http://10.128.0.4:8090;
  }
}
